// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhvmkjvrzhdarrybmgtc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZodm1ranZyemhkYXJyeWJtZ3RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MzM2MjEsImV4cCI6MjA2MDUwOTYyMX0.RrFTA_NiOb2D6ufBBrbl1cnhbOUpcY-o74zpqcMi53U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});